<?php
$e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$isClient=($organization['account_type']??'')==='ClientCompany';$isAgency=($organization['account_type']??'')==='Agency';
$scopeLabels=['projects'=>'Projets','content'=>'Contenus','validation'=>'Validations','publishing'=>'Publication','analytics'=>'Statistiques','history'=>'Historique','users'=>'Utilisateurs'];
$active=count(array_filter($grants,fn($g)=>$g['status']==='Active'));$pending=count(array_filter($grants,fn($g)=>$g['status']==='Pending'));
$scopeFields=static function(array$scope=[])use($scopeLabels,$e){foreach($scopeLabels as$key=>$label){$checked=$key==='projects'||!empty($scope[$key]);echo '<label class="access-scope-option"><input type="checkbox" name="scope['.$e($key).']" value="1" '.($checked?'checked':'').' '.($key==='projects'?'disabled':'').'><span><b>'.$e($label).'</b><small>'.($key==='projects'?'Acces minimal obligatoire':'Autorisation facultative').'</small></span></label>';if($key==='projects')echo '<input type="hidden" name="scope[projects]" value="1">';}};
?>
<link rel="stylesheet" href="<?= $e(app_url('/public/assets/agency-access.css')) ?>">
<section class="access-page">
 <header class="access-hero"><div><span class="access-kicker">Relations securisees</span><h1>Connexions agence–client</h1><p><?= $isClient?'Vous restez proprietaire de vos donnees et choisissez exactement ce que chaque agence peut utiliser.':'Connectez un client avec son accord et travaillez dans le perimetre qu il vous confie.'?></p></div><span class="access-org-badge"><?= $e($organization['name'])?> · <?= $isClient?'Compte client':($isAgency?'Agence':'Plateforme')?></span></header>
 <div class="access-stats"><article><span>Relations</span><strong><?= count($grants)?></strong></article><article><span>Actives</span><strong><?= $active?></strong></article><article><span>En attente</span><strong><?= $pending?></strong></article><article><span>Principe</span><strong>Acces minimal</strong></article></div>
 <?php if($generatedCode):?><section class="access-code-reveal"><div><span>Code temporaire</span><strong data-sync-code><?= $e($generatedCode)?></strong><small>Valable 30 minutes · usage unique</small></div><button class="button secondary" type="button" data-copy-code>Copier le code</button></section><?php endif?>
 <div class="access-onboarding">
  <?php if($isClient):?>
  <section class="panel access-action-card"><div class="access-step">Option 1</div><h2>Donner un code a une agence</h2><p>L’agence saisit ce code, puis vous validez sa demande et ses droits depuis cet espace.</p><form method="post"><button class="button" name="action" value="generate_code">Generer un code securise</button></form></section>
  <section class="panel access-action-card"><div class="access-step">Option 2</div><h2>Inviter une agence inscrite</h2><p>Choisissez l’agence et le perimetre. Elle devra accepter votre invitation.</p><form method="post" class="access-invite-form"><label>Agence<select name="agency_organization_id" required><option value="">Selectionner</option><?php foreach($agencies as$a):?><option value="<?= (int)$a['id']?>"><?= $e($a['name'])?></option><?php endforeach?></select></label><fieldset><legend>Droits proposes</legend><div class="access-scope-grid"><?php $scopeFields(['projects'=>true,'content'=>true,'validation'=>true,'analytics'=>true,'history'=>true]);?></div></fieldset><button class="button" name="action" value="invite_agency">Envoyer l’invitation</button></form></section>
  <?php elseif($isAgency):?>
  <section class="panel access-action-card access-action-wide"><div class="access-step">Connexion par code</div><h2>Ajouter un client a votre portefeuille</h2><p>Demandez au client son code temporaire. La saisie du code cree seulement une demande : le client garde la validation finale.</p><form method="post" class="access-code-form"><label>Code du client<input name="sync_code" required maxlength="12" autocomplete="off" placeholder="AB12-CD34"></label><fieldset><legend>Droits demandes</legend><div class="access-scope-grid"><?php $scopeFields(['projects'=>true,'content'=>true,'validation'=>true,'analytics'=>true,'history'=>true]);?></div></fieldset><button class="button" name="action" value="connect_with_code">Envoyer la demande</button></form></section>
  <?php endif?>
 </div>
 <section class="panel access-relations"><div class="access-section-head"><div><span class="access-kicker">Portefeuille</span><h2>Relations et permissions</h2><p>Les modifications de droits et les revocations prennent effet immediatement.</p></div><span class="access-count"><?= count($grants)?></span></div>
  <div class="access-relation-list"><?php foreach($grants as$g):$currentIsClient=(int)$organization['id']===(int)$g['client_organization_id'];$mustDecide=$g['status']==='Pending'&&(($g['request_origin']==='AgencyCode'&&$currentIsClient)||($g['request_origin']==='ClientInvitation'&&!$currentIsClient));?>
   <article class="access-relation"><div class="access-relation-main"><div class="access-avatar"><?= $e(mb_substr($currentIsClient?$g['agency_name']:$g['client_name'],0,1))?></div><div><span class="access-kicker"><?= $currentIsClient?'Agence autorisee':'Entreprise cliente'?></span><h3><?= $e($currentIsClient?$g['agency_name']:$g['client_name'])?></h3><div class="access-meta"><span class="access-status status-<?= strtolower($e($g['status']))?>"><?= $e($g['status'])?></span><span><?= $g['request_origin']==='AgencyCode'?'Demande par code':($g['request_origin']==='ClientInvitation'?'Invitation client':'Creation administrative')?></span><span><?= $e(date('d/m/Y H:i',strtotime($g['updated_at'])))?></span></div></div></div>
    <div class="access-scope-summary"><?php foreach($scopeLabels as$key=>$label):if(!empty($g['scope'][$key])):?><span><?= $e($label)?></span><?php endif;endforeach?></div>
    <?php if($mustDecide):?><form method="post" class="access-decision"><input type="hidden" name="grant_id" value="<?= (int)$g['id']?>"><button class="button secondary" name="action" value="decline">Refuser</button><button class="button" name="action" value="approve">Accepter la connexion</button></form><?php endif?>
    <?php if($g['status']==='Active'):?><details class="access-permission-editor"><summary>Gerer cette connexion <b>⌄</b></summary><form method="post"><input type="hidden" name="grant_id" value="<?= (int)$g['id']?>"><?php if($currentIsClient):?><div class="access-scope-grid"><?php $scopeFields($g['scope']);?></div><div class="access-editor-actions"><button class="button" name="action" value="update_permissions">Enregistrer les droits</button><button class="button danger" name="action" value="revoke" onclick="return confirm('Revoquer immediatement cet acces ?')">Revoquer l’acces</button></div><?php else:?><p>Seul le client proprietaire peut etendre les droits. Vous pouvez quitter cette relation a tout moment.</p><button class="button danger" name="action" value="revoke" onclick="return confirm('Quitter cette connexion client ?')">Quitter la connexion</button><?php endif?></form></details><?php endif?>
   </article><?php endforeach?><?php if(!$grants):?><div class="access-empty"><strong>Aucune relation</strong><span>Utilisez un code ou envoyez une invitation pour commencer.</span></div><?php endif?></div>
 </section>
 <section class="panel access-activity"><div class="access-section-head"><div><span class="access-kicker">Audit</span><h2>Journal d’activite</h2><p>Historique des operations sensibles liees aux connexions.</p></div></div><div class="access-timeline"><?php foreach($activity as$log):?><article><i></i><div><strong><?= $e(str_replace(['agency_access.','sync_code.'],['Connexion : ','Code : '],$log['action']))?></strong><span><?= $e($log['actor_name']?:'Systeme')?> · <?= $e(date('d/m/Y H:i',strtotime($log['created_at'])))?></span></div></article><?php endforeach?><?php if(!$activity):?><p class="access-muted">Aucune activite enregistree.</p><?php endif?></div></section>
</section>
<script>document.querySelector('[data-copy-code]')?.addEventListener('click',async e=>{const code=document.querySelector('[data-sync-code]')?.textContent.trim();if(!code)return;await navigator.clipboard.writeText(code);e.currentTarget.textContent='Code copie'});</script>