<?php
class WorkflowNotificationService {
    private PDO $db;
    public function __construct() { $this->db = Database::getConnection(); }

    public function sendProgressReport(int $taskId,int $senderId,string $message): bool {
        $message=trim($message);if($message==='')throw new RuntimeException('Rédigez un bref rapport d’avancement.');
        $stmt=$this->db->prepare("SELECT tp.*,p.nom projet_nom,p.charge_compte_id,p.charge_clientele_id,p.cm_id,p.createur_id,p.designer_id,p.cadreur_id,p.videaste_id,c.entreprise client_nom,s.nom sender_name,s.email sender_email FROM taches_pipeline tp JOIN projets p ON p.id=tp.projet_id JOIN clients c ON c.id=p.client_id JOIN users s ON s.id=:sender WHERE tp.id=:task LIMIT 1");
        $stmt->execute(['sender'=>$senderId,'task'=>$taskId]);$task=$stmt->fetch(PDO::FETCH_ASSOC);if(!$task)throw new RuntimeException('Tâche introuvable.');TenantGuard::assertProject((int)$task['projet_id']);
        $next=$this->db->prepare("SELECT tp.id,tp.titre,tp.type_tache,tp.auteur_id,u.nom,u.email FROM taches_pipeline tp LEFT JOIN users u ON u.id=tp.auteur_id WHERE tp.parent_task_id=:task AND tp.statut<>'Annulee' ORDER BY tp.ordre_pipeline,tp.id LIMIT 1");$next->execute(['task'=>$taskId]);$nextTask=$next->fetch(PDO::FETCH_ASSOC)?:[];
        $userIds=array_values(array_unique(array_filter(array_map('intval',[$task['charge_compte_id'],$task['charge_clientele_id'],$task['cm_id'],$task['createur_id'],$task['designer_id'],$task['cadreur_id'],$task['videaste_id']]))));
        $validationNext=in_array((string)($nextTask['type_tache']??''),['Validation interne','Validation client'],true);
        $primaryId=$validationNext?(int)($nextTask['auteur_id']??0):(int)($task['charge_compte_id']??0);
        if($primaryId<=0)$primaryId=(int)($nextTask['auteur_id']??0);if($primaryId<=0)throw new RuntimeException('Aucun responsable avec une adresse e-mail n’est défini.');
        if(!$validationNext&&!empty($nextTask['auteur_id']))$userIds[]=(int)$nextTask['auteur_id'];
        $userIds=array_values(array_unique(array_filter($userIds,static fn($id)=>$id!==$senderId)));
        $people=$this->usersByIds(array_values(array_unique(array_merge([$primaryId],$userIds))));$primary=$people[$primaryId]??null;
        if(!$primary||!filter_var($primary['email']??'',FILTER_VALIDATE_EMAIL))throw new RuntimeException('Le destinataire principal n’a pas d’adresse e-mail valide.');
        $cc=[];if(!$validationNext){foreach($userIds as$id){$email=trim((string)($people[$id]['email']??''));if($id!==$primaryId&&filter_var($email,FILTER_VALIDATE_EMAIL))$cc[]=$email;}}
        $subject='Avancement · '.$task['client_nom'].' · '.$task['titre'];$lines=['Rapport envoyé par '.($task['sender_name']?:'Un membre de l’équipe').'.','','Client : '.$task['client_nom'],'Projet : '.$task['projet_nom'],'Étape : '.$task['titre'],'Statut : '.$task['statut'],'Échéance : '.($task['deadline']?:'Non définie')];
        if($nextTask)$lines[]='Étape suivante : '.$nextTask['titre'].' · '.($nextTask['nom']?:'Non assignée');$lines[]='';$lines[]=$message;
        $url=route_url('/calendrier/task/'.$taskId);$sent=StraxMailTransport::send([$primary['email']],$subject,implode("\n",$lines),$url,'Ouvrir la tâche',$cc,(string)($task['sender_email']??''));
        $save=$this->db->prepare('INSERT INTO workflow_progress_reports(tenant_id,task_id,sender_id,subject,message,primary_recipient,cc_recipients,delivery_status) VALUES(:tenant,:task,:sender,:subject,:message,:primary,:cc,:status)');$save->execute(['tenant'=>TenantGuard::tenantId(),'task'=>$taskId,'sender'=>$senderId,'subject'=>$subject,'message'=>$message,'primary'=>$primary['email'],'cc'=>implode(',',$cc),'status'=>$sent?'Sent':'Failed']);
        return $sent;
    }

    public function sendCalendarFlash(array $projectIds,int $senderId,string $month,string $message): bool {
        $projectIds=array_values(array_unique(array_filter(array_map('intval',$projectIds))));
        if(!$projectIds)throw new RuntimeException('Sélectionnez au moins un calendrier.');
        if(count($projectIds)>50)throw new RuntimeException('Un flash peut contenir au maximum 50 projets.');
        if(!preg_match('/^\d{4}-(0[1-9]|1[0-2])$/',$month))throw new RuntimeException('Mois du flash invalide.');
        $message=trim($message);if($message==='')throw new RuntimeException('Ajoutez une synthèse au flash d’avancement.');
        $senderStmt=$this->db->prepare("SELECT id,nom,email FROM users WHERE id=:id AND statut='Actif'");$senderStmt->execute(['id'=>$senderId]);$sender=$senderStmt->fetch(PDO::FETCH_ASSOC);if(!$sender)throw new RuntimeException('Auteur du flash introuvable.');
        $projectStmt=$this->db->prepare("SELECT p.id,p.nom,p.charge_compte_id,p.charge_clientele_id,p.cm_id,c.entreprise client_nom,COUNT(DISTINCT li.id) tasks_total,COUNT(DISTINCT CASE WHEN li.statut='Publie' THEN li.id END) tasks_done,COUNT(DISTINCT CASE WHEN tp.statut IN ('A faire','En cours') AND tp.deadline<CURDATE() THEN tp.id END) tasks_late,MIN(CASE WHEN tp.statut IN ('A faire','En cours') THEN tp.deadline END) next_deadline FROM projets p JOIN clients c ON c.id=p.client_id LEFT JOIN plans_mensuels pm ON pm.projet_id=p.id AND pm.periode_mois=:period LEFT JOIN livrable_items li ON li.plan_mensuel_id=pm.id AND COALESCE(li.statut,'')<>'Annule' LEFT JOIN taches_pipeline tp ON tp.plan_mensuel_id=pm.id AND tp.statut<>'Annulee' WHERE p.id=:project GROUP BY p.id,c.id");
        $activeStmt=$this->db->prepare("SELECT tp.id,tp.titre,tp.type_tache,tp.auteur_id,u.nom,u.email FROM taches_pipeline tp JOIN plans_mensuels pm ON pm.id=tp.plan_mensuel_id LEFT JOIN users u ON u.id=tp.auteur_id WHERE pm.projet_id=:project AND pm.periode_mois=:period AND tp.statut IN ('A faire','En cours') ORDER BY tp.ordre_pipeline,tp.deadline,tp.id LIMIT 1");
        $stageStmt=$this->db->prepare("SELECT tp.type_tache,COUNT(DISTINCT tp.livrable_item_id) total,COUNT(DISTINCT CASE WHEN tp.statut='Terminee' THEN tp.livrable_item_id END) done FROM taches_pipeline tp JOIN plans_mensuels pm ON pm.id=tp.plan_mensuel_id JOIN livrable_items li ON li.id=tp.livrable_item_id AND COALESCE(li.statut,'')<>'Annule' WHERE pm.projet_id=:project AND pm.periode_mois=:period AND tp.statut<>'Annulee' GROUP BY tp.type_tache UNION ALL SELECT 'Fiche contenu',COUNT(DISTINCT li.id),COUNT(DISTINCT CASE WHEN COALESCE(TRIM(ct.sujet),'')<>'' AND COALESCE(TRIM(ct.message),'')<>'' AND COALESCE(TRIM(ct.objectif_publication),'')<>'' AND COALESCE(TRIM(ct.cible_libre),'')<>'' AND COALESCE(TRIM(ct.reseau_cible),'')<>'' THEN li.id END) FROM livrable_items li JOIN plans_mensuels pm ON pm.id=li.plan_mensuel_id LEFT JOIN contenus ct ON ct.livrable_item_id=li.id WHERE pm.projet_id=:project AND pm.periode_mois=:period AND COALESCE(li.statut,'')<>'Annule'");
        $rows=[];$primaryIds=[];$copyIds=[];$period=$month.'-01';
        foreach($projectIds as$projectId){TenantGuard::assertProject($projectId);$projectStmt->execute(['period'=>$period,'project'=>$projectId]);$row=$projectStmt->fetch(PDO::FETCH_ASSOC);if(!$row)continue;$activeStmt->execute(['project'=>$projectId,'period'=>$period]);$active=$activeStmt->fetch(PDO::FETCH_ASSOC)?:[];$stageStmt->execute(['project'=>$projectId,'period'=>$period]);$row['stages']=$stageStmt->fetchAll(PDO::FETCH_ASSOC);$row['active']=$active;$rows[]=$row;$isValidation=in_array((string)($active['type_tache']??''),['Validation interne','Validation client'],true);$primary=$isValidation?(int)($active['auteur_id']??0):(int)($row['charge_compte_id']??0);if($primary<=0)$primary=(int)($active['auteur_id']??0);if($primary>0)$primaryIds[]=$primary;if(!$isValidation){foreach([$row['charge_compte_id'],$row['charge_clientele_id'],$row['cm_id'],$active['auteur_id']??0]as$id){$id=(int)$id;if($id>0)$copyIds[]=$id;}}}
        if(!$rows)throw new RuntimeException('Aucun calendrier accessible dans la sélection.');
        $recipientIds=array_values(array_unique(array_filter(array_merge($primaryIds,$copyIds),static fn($id)=>(int)$id!==$senderId)));$people=$this->usersByIds($recipientIds);
        $candidateIds=array_values(array_unique(array_merge($primaryIds,$recipientIds)));$candidateIds=array_values(array_filter($candidateIds,static fn($id)=>(int)$id!==$senderId&&filter_var($people[(int)$id]['email']??'',FILTER_VALIDATE_EMAIL)));
        if(!$candidateIds)throw new RuntimeException('Aucun responsable sélectionné ne possède une adresse e-mail valide.');
        $lines=['Flash calendrier envoyé par '.($sender['nom']?:'Un membre de l’équipe').'.','Période : '.$month,'Calendriers : '.count($rows),''];$snapshot=[];
        foreach($rows as$row){$total=(int)$row['tasks_total'];$done=(int)$row['tasks_done'];$rate=$total>0?round($done*100/$total):0;$active=$row['active'];$lines[]=$row['client_nom'].' · '.$row['nom'];$lines[]='Avancement : '.$done.'/'.$total.' ('.$rate.' %) · Retards : '.(int)$row['tasks_late'].' · Prochaine échéance : '.($row['next_deadline']?:'Aucune');$lines[]='Étape active : '.($active['titre']??'Aucune').' · '.($active['nom']??'Non assignée');$lines[]='';$snapshot[]=['project_id'=>(int)$row['id'],'client'=>$row['client_nom'],'project'=>$row['nom'],'done'=>$done,'total'=>$total,'late'=>(int)$row['tasks_late'],'active_task_id'=>(int)($active['id']??0)];}
        $lines[]='Synthèse';$lines[]=$message;$subject='Flash calendrier · '.$month.' · '.count($rows).' projet(s)';$url=route_url('/calendrier').'?month='.urlencode($month);$htmlMessage=$this->calendarFlashHtml($rows,$sender,$month,$message);$sent=false;$primary=null;$cc=[];
        foreach($candidateIds as$candidateId){
            $primary=(int)$candidateId;$cc=[];
            foreach($recipientIds as$id){$email=trim((string)($people[$id]['email']??''));if($id!==$primary&&filter_var($email,FILTER_VALIDATE_EMAIL))$cc[$email]=true;}
            $sent=StraxMailTransport::send([$people[$primary]['email']],$subject,implode("\n",$lines),$url,'Ouvrir le pilotage',array_keys($cc),(string)($sender['email']??''),$htmlMessage);
            if($sent)break;
            $mailError=StraxMailTransport::lastError();
            if(($mailError['stage']??'')!=='recipient')break;
        }
        $save=$this->db->prepare('INSERT INTO calendar_progress_flashes(tenant_id,sender_id,period_month,project_ids,subject,message,snapshot_json,primary_recipient,cc_recipients,delivery_status) VALUES(:tenant,:sender,:period,:projects,:subject,:message,:snapshot,:primary,:cc,:status)');$save->execute(['tenant'=>TenantGuard::tenantId(),'sender'=>$senderId,'period'=>$period,'projects'=>json_encode($projectIds),'subject'=>$subject,'message'=>$message,'snapshot'=>json_encode($snapshot,JSON_UNESCAPED_UNICODE),'primary'=>$people[$primary]['email'],'cc'=>implode(',',array_keys($cc)),'status'=>$sent?'Sent':'Failed']);return$sent;
    }

    private function calendarFlashHtml(array $rows,array $sender,string $month,string $message): string {
        $e=static fn($value)=>htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
        $columns=['Fiches'=>['Fiche contenu'],'Briefs'=>['Brief'],'Scripts'=>['Script'],'Prod. visuels'=>['Production'],'Prod. vidéos'=>['Montage'],'Validation int.'=>['Validation interne'],'Validation client'=>['Validation client'],'Publication'=>['Publication'],'Collecte'=>['Collecte KPI']];
        $html='<p style="margin:0 0 6px;color:#64748b">Envoyé par <strong style="color:#334155">'.$e($sender['nom']?:'Un membre de l’équipe').'</strong> · Période <strong style="color:#334155">'.$e($month).'</strong></p><p style="margin:0 0 20px;color:#64748b">Lecture : nombre d’étapes terminées / nombre total d’étapes prévues.</p><div style="overflow-x:auto"><table role="table" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;font-size:12px;min-width:760px"><thead><tr style="background:#10243c;color:#fff"><th align="left" style="padding:10px;border:1px solid #dbe5ef">Client / projet</th>';
        foreach(array_keys($columns)as$label)$html.='<th align="center" style="padding:10px 6px;border:1px solid #dbe5ef">'.$e($label).'</th>';
        $html.='<th align="center" style="padding:10px 6px;border:1px solid #dbe5ef">Total</th><th align="center" style="padding:10px 6px;border:1px solid #dbe5ef">Retards</th></tr></thead><tbody>';
        foreach($rows as$row){$stageValues=[];foreach((array)$row['stages']as$stage)$stageValues[(string)$stage['type_tache']]=[(int)$stage['done'],(int)$stage['total']];$html.='<tr><td style="padding:10px;border:1px solid #dbe5ef"><strong>'.$e($row['client_nom']).'</strong><br><span style="color:#64748b">'.$e($row['nom']).'</span></td>';
            foreach($columns as$types){$done=0;$total=0;foreach($types as$type){$done+=$stageValues[$type][0]??0;$total+=$stageValues[$type][1]??0;}$color=$total>0&&$done===$total?'#287a55':($done>0?'#9a6700':'#64748b');$html.='<td align="center" style="padding:10px 6px;border:1px solid #dbe5ef;color:'.$color.';font-weight:bold">'.($total?$done.'/'.$total:'—').'</td>';}
            $html.='<td align="center" style="padding:10px 6px;border:1px solid #dbe5ef;font-weight:bold">'.(int)$row['tasks_done'].'/'.(int)$row['tasks_total'].'</td><td align="center" style="padding:10px 6px;border:1px solid #dbe5ef;color:'.((int)$row['tasks_late']?'#b42318':'#287a55').';font-weight:bold">'.(int)$row['tasks_late'].'</td></tr>';}
        $html.='</tbody></table></div><div style="margin:22px 0;padding:16px;background:#f3f7fb;border-left:4px solid #3977ad;border-radius:8px"><strong style="display:block;margin-bottom:8px;color:#10243c">Synthèse</strong><div style="line-height:1.6">'.nl2br($e($message)).'</div></div>';
        return$html;
    }

    public function sendDeadlineDigests(int $daysAhead=3): array {
        $daysAhead=max(1,min(14,$daysAhead));$tenant=TenantGuard::tenantId();
        $stmt=$this->db->prepare("SELECT tp.id,tp.titre,tp.deadline,tp.statut,p.nom projet_nom,c.entreprise client_nom,u.email,u.nom FROM taches_pipeline tp JOIN projets p ON p.id=tp.projet_id JOIN clients c ON c.id=p.client_id JOIN users u ON u.id=tp.auteur_id WHERE c.tenant_id=:tenant AND tp.statut IN ('A faire','En cours') AND tp.deadline IS NOT NULL AND tp.deadline<=DATE_ADD(CURDATE(),INTERVAL :days DAY) AND COALESCE(p.statut,'Actif') NOT IN ('Suspendu','Termine','Terminé','Archive') ORDER BY u.email,tp.deadline,tp.id");$stmt->bindValue(':tenant',$tenant,PDO::PARAM_INT);$stmt->bindValue(':days',$daysAhead,PDO::PARAM_INT);$stmt->execute();$groups=[];foreach($stmt->fetchAll(PDO::FETCH_ASSOC)as$row){if(filter_var($row['email'],FILTER_VALIDATE_EMAIL))$groups[$row['email']][]=$row;}
        $sent=0;$skipped=0;foreach($groups as$email=>$tasks){$key='deadline-digest:'.date('Y-m-d').':'.hash('sha256',$email);if($this->alreadyLogged($tenant,$key,$email)){$skipped++;continue;}$lines=['Bonjour '.($tasks[0]['nom']?:''),'',"Voici vos échéances nécessitant une attention :",''];foreach($tasks as$t){$delay=(strtotime($t['deadline'])<strtotime(date('Y-m-d')))?'EN RETARD':'À VENIR';$lines[]='['.$delay.'] '.$t['deadline'].' · '.$t['client_nom'].' · '.$t['projet_nom'].' · '.$t['titre'];}$ok=StraxMailTransport::send([$email],'Échéances Strax · '.date('d/m/Y'),implode("\n",$lines),route_url('/'),'Ouvrir le tableau de bord');$this->log($tenant,$key,'deadline_digest',$email,$ok);$sent+=(int)$ok;}
        return compact('sent','skipped');
    }
    public function reportsForTask(int$taskId): array {$stmt=$this->db->prepare('SELECT r.*,u.nom sender_name FROM workflow_progress_reports r JOIN users u ON u.id=r.sender_id WHERE r.tenant_id=:tenant AND r.task_id=:task ORDER BY r.id DESC LIMIT 20');$stmt->execute(['tenant'=>TenantGuard::tenantId(),'task'=>$taskId]);return$stmt->fetchAll(PDO::FETCH_ASSOC);}
    private function usersByIds(array$ids): array {if(!$ids)return[];$marks=implode(',',array_fill(0,count($ids),'?'));$stmt=$this->db->prepare("SELECT id,nom,email FROM users WHERE id IN ($marks) AND statut='Actif'");$stmt->execute($ids);$out=[];foreach($stmt->fetchAll(PDO::FETCH_ASSOC)as$row)$out[(int)$row['id']]=$row;return$out;}
    private function alreadyLogged(int$t,string$key,string$email): bool {$s=$this->db->prepare("SELECT 1 FROM workflow_notification_log WHERE tenant_id=? AND notification_key=? AND recipient_email=? AND delivery_status='Sent'");$s->execute([$t,$key,$email]);return(bool)$s->fetchColumn();}
    private function log(int$t,string$key,string$type,string$email,bool$ok): void {$s=$this->db->prepare('INSERT INTO workflow_notification_log(tenant_id,notification_key,notification_type,recipient_email,delivery_status) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE delivery_status=VALUES(delivery_status),created_at=CURRENT_TIMESTAMP');$s->execute([$t,$key,$type,$email,$ok?'Sent':'Failed']);}
}
