<?php
class SocialPublishingModel extends Model {
    public const PROVIDERS=['facebook'=>'Facebook','instagram'=>'Instagram','linkedin'=>'LinkedIn','tiktok'=>'TikTok','youtube'=>'YouTube','x'=>'X'];

    public function dashboardData(): array {
        $tenant=TenantGuard::tenantId();
        $connections=$this->db->prepare('SELECT sc.*,c.entreprise client_name,(SELECT GROUP_CONCAT(scp.project_id ORDER BY scp.project_id) FROM social_connection_projects scp WHERE scp.connection_id=sc.id) project_ids FROM social_connections sc LEFT JOIN clients c ON c.id=sc.client_id WHERE sc.tenant_id=:tenant ORDER BY sc.status="Connected" DESC,sc.provider,sc.account_label');$connections->execute(['tenant'=>$tenant]);
        $publications=$this->db->prepare('SELECT sp.*,c.entreprise client_name,COUNT(t.id) target_count,SUM(t.status="Published") published_count,SUM(t.status="Failed") failed_count,SUM(t.status IN ("Queued","Retrying","Processing")) queued_count FROM social_publications sp JOIN clients c ON c.id=sp.client_id LEFT JOIN social_publication_targets t ON t.publication_id=sp.id WHERE sp.tenant_id=:tenant GROUP BY sp.id ORDER BY sp.created_at DESC LIMIT 40');$publications->execute(['tenant'=>$tenant]);$publicationRows=$publications->fetchAll(PDO::FETCH_ASSOC);
        $targetsByPublication=[];if($publicationRows){$ids=array_map(static fn($r)=>(int)$r['id'],$publicationRows);$marks=implode(',',array_fill(0,count($ids),'?'));$stmt=$this->db->prepare("SELECT t.*,sc.account_label FROM social_publication_targets t JOIN social_connections sc ON sc.id=t.connection_id WHERE t.publication_id IN ($marks) ORDER BY t.id");$stmt->execute($ids);foreach($stmt->fetchAll(PDO::FETCH_ASSOC)as$row)$targetsByPublication[(int)$row['publication_id']][]=$row;}
        $stats=$this->db->prepare('SELECT COUNT(*) total,SUM(status IN ("Queued","Retrying","Processing")) queued,SUM(status="Published" AND remote_deleted_at IS NULL) published,SUM(status="Failed") failed FROM social_publication_targets WHERE publication_id IN (SELECT id FROM social_publications WHERE tenant_id=:tenant)');$stats->execute(['tenant'=>$tenant]);
        return['connections'=>$connections->fetchAll(PDO::FETCH_ASSOC),'publications'=>$publicationRows,'targetsByPublication'=>$targetsByPublication,'stats'=>$stats->fetch(PDO::FETCH_ASSOC)?:[]];
    }
    public function projects(): array {$stmt=$this->db->prepare("SELECT p.id,p.client_id,p.nom FROM projets p JOIN clients c ON c.id=p.client_id WHERE c.tenant_id=:tenant AND p.statut<>'Archive' ORDER BY c.entreprise,p.nom");$stmt->execute(['tenant'=>TenantGuard::tenantId()]);return$stmt->fetchAll(PDO::FETCH_ASSOC);}
    public function clients(): array {$stmt=$this->db->prepare('SELECT id,COALESCE(NULLIF(entreprise,""),nom) name FROM clients WHERE tenant_id=:tenant AND statut="Actif" ORDER BY name');$stmt->execute(['tenant'=>TenantGuard::tenantId()]);return$stmt->fetchAll(PDO::FETCH_ASSOC);}
    public function saveConnection(array$input,int$userId): int {$client=(int)($input['client_id']??0);TenantGuard::assertClient($client);$provider=strtolower(trim((string)($input['provider']??'')));if(!isset(self::PROVIDERS[$provider]))throw new RuntimeException('Réseau non pris en charge.');$label=trim((string)($input['account_label']??''));if($label==='')throw new RuntimeException('Nom du compte obligatoire.');$stmt=$this->db->prepare("INSERT INTO social_connections(tenant_id,organization_id,client_id,provider,account_label,external_account_id,account_type,status,connected_by) VALUES(:tenant,:organization,:client,:provider,:label,:external_id,:account_type,'Pending',:user)");$ctx=OrganizationContext::forUser($_SESSION['user']??[]);$stmt->execute(['tenant'=>TenantGuard::tenantId(),'organization'=>(int)($ctx['id']??$ctx['organization_id']??0)?:null,'client'=>$client,'provider'=>$provider,'label'=>$label,'external_id'=>trim((string)($input['external_account_id']??''))?:null,'account_type'=>trim((string)($input['account_type']??'Page')),'user'=>$userId]);return(int)$this->db->lastInsertId();}

    public function createPublication(array$input,array$file,int$userId): int {
        $client=(int)($input['client_id']??0);TenantGuard::assertClient($client);$projectId=(int)($input['project_id']??0);if(!$projectId)throw new RuntimeException('Sélectionnez le projet de la publication.');$projectCheck=$this->db->prepare('SELECT p.id FROM projets p JOIN clients c ON c.id=p.client_id WHERE p.id=:project AND p.client_id=:client AND c.tenant_id=:tenant');$projectCheck->execute(['project'=>$projectId,'client'=>$client,'tenant'=>TenantGuard::tenantId()]);if(!$projectCheck->fetchColumn())throw new RuntimeException('Le projet sélectionné n appartient pas à ce client.');$targetIds=array_values(array_unique(array_filter(array_map('intval',(array)($input['connection_ids']??[])))));if(!$targetIds)throw new RuntimeException('Sélectionnez au moins une destination.');
        $connections=[];$check=$this->db->prepare('SELECT * FROM social_connections WHERE id=:id AND tenant_id=:tenant AND client_id=:client AND status="Connected"');foreach($targetIds as$id){$check->execute(['id'=>$id,'tenant'=>TenantGuard::tenantId(),'client'=>$client]);$row=$check->fetch(PDO::FETCH_ASSOC);if(!$row)throw new RuntimeException('Une destination n est pas connectée.');$scope=$this->db->prepare('SELECT COUNT(*) total,SUM(project_id=:project) allowed FROM social_connection_projects WHERE connection_id=:connection AND tenant_id=:tenant');$scope->execute(['project'=>$projectId,'connection'=>$id,'tenant'=>TenantGuard::tenantId()]);$access=$scope->fetch(PDO::FETCH_ASSOC);if((int)$access['total']>0&&(int)$access['allowed']===0)throw new RuntimeException('Une destination Meta n est pas autorisée pour ce projet.');$this->assertPublishPermission($row);$connections[]=$row;}
        $title=trim((string)($input['master_title']??''));$caption=trim((string)($input['master_caption']??''));if($title===''||$caption==='')throw new RuntimeException('Titre et contenu maître obligatoires.');
        $mode=($input['publish_mode']??'Scheduled')==='Now'?'Now':'Scheduled';$scheduled=trim((string)($input['scheduled_at']??''));if($mode==='Scheduled'&&($scheduled===''||strtotime($scheduled)===false))throw new RuntimeException('Date de programmation obligatoire.');if($mode==='Scheduled'&&strtotime($scheduled)<time()-60)throw new RuntimeException('La programmation doit être dans le futur.');
        $mediaUrl=trim((string)($input['media_url']??''));$mediaPath=null;$mediaMime=null;if(!empty($file['tmp_name'])){[$mediaUrl,$mediaPath,$mediaMime]=$this->storeUpload($file);}elseif($mediaUrl!==''&&!filter_var($mediaUrl,FILTER_VALIDATE_URL))throw new RuntimeException('URL du média invalide.');if($mediaUrl!==''&&!str_starts_with(strtolower($mediaUrl),'https://'))throw new RuntimeException('Meta exige une URL de média publique en HTTPS.');
        foreach($connections as$c){if($c['provider']==='instagram'&&$mediaUrl==='')throw new RuntimeException('Instagram exige une image JPEG publique.');if($c['provider']==='instagram'&&$mediaMime!==null&&!in_array($mediaMime,['image/jpeg'],true))throw new RuntimeException('Pour Instagram, importez une image JPEG.');}
        $approval=!empty($input['submit_approval'])?'Pending':'Draft';$this->db->beginTransaction();try{$ctx=OrganizationContext::forUser($_SESSION['user']??[]);$stmt=$this->db->prepare('INSERT INTO social_publications(tenant_id,organization_id,client_id,project_id,content_id,master_title,master_caption,media_url,media_path,media_mime,publish_mode,scheduled_at,approval_status,created_by) VALUES(:tenant,:organization,:client,:project,:content,:title,:caption,:media,:path,:mime,:mode,:scheduled,:approval,:user)');$stmt->execute(['tenant'=>TenantGuard::tenantId(),'organization'=>(int)($ctx['id']??$ctx['organization_id']??0)?:null,'client'=>$client,'project'=>(int)($input['project_id']??0)?:null,'content'=>(int)($input['content_id']??0)?:null,'title'=>$title,'caption'=>$caption,'media'=>$mediaUrl?:null,'path'=>$mediaPath,'mime'=>$mediaMime,'mode'=>$mode,'scheduled'=>$mode==='Scheduled'?date('Y-m-d H:i:s',strtotime($scheduled)):date('Y-m-d H:i:s'),'approval'=>$approval,'user'=>$userId]);$publication=(int)$this->db->lastInsertId();$insert=$this->db->prepare('INSERT INTO social_publication_targets(publication_id,connection_id,provider,adapted_caption,status,next_attempt_at) VALUES(:publication,:connection,:provider,:caption,"WaitingApproval",:next)');foreach($connections as$c){$variant=trim((string)($input['variant'][$c['id']]??''))?:$caption;$insert->execute(['publication'=>$publication,'connection'=>$c['id'],'provider'=>$c['provider'],'caption'=>$variant,'next'=>$mode==='Now'?date('Y-m-d H:i:s'):date('Y-m-d H:i:s',strtotime($scheduled))]);}$this->event($publication,null,'created',$approval,'Publication créée',$userId);$this->db->commit();return$publication;}catch(Throwable$e){if($this->db->inTransaction())$this->db->rollBack();if($mediaPath&&is_file(UPLOADS_PATH.'/'.$mediaPath))@unlink(UPLOADS_PATH.'/'.$mediaPath);throw$e;}
    }
    public function submit(int$id,int$userId): void {$stmt=$this->db->prepare("UPDATE social_publications SET approval_status='Pending' WHERE id=:id AND tenant_id=:tenant AND approval_status='Draft'");$stmt->execute(['id'=>$id,'tenant'=>TenantGuard::tenantId()]);if(!$stmt->rowCount())throw new RuntimeException('Brouillon introuvable.');$this->event($id,null,'submitted','Pending','Publication envoyée en validation',$userId);}
    public function approve(int$id,int$userId): void {$stmt=$this->db->prepare('UPDATE social_publications SET approval_status="Approved",approved_by=:user,approved_at=NOW() WHERE id=:id AND tenant_id=:tenant AND approval_status="Pending"');$stmt->execute(['user'=>$userId,'id'=>$id,'tenant'=>TenantGuard::tenantId()]);if(!$stmt->rowCount())throw new RuntimeException('Publication non disponible pour validation.');$this->db->prepare('UPDATE social_publication_targets SET status="Queued" WHERE publication_id=:id AND status="WaitingApproval"')->execute(['id'=>$id]);$this->event($id,null,'approved','Queued','Publication approuvée et placée en file',$userId);}
    public function retry(int$targetId,int$userId): void {$stmt=$this->db->prepare('UPDATE social_publication_targets t JOIN social_publications p ON p.id=t.publication_id SET t.status="Queued",t.next_attempt_at=NOW(),t.last_error=NULL WHERE t.id=:id AND p.tenant_id=:tenant AND t.status="Failed"');$stmt->execute(['id'=>$targetId,'tenant'=>TenantGuard::tenantId()]);if(!$stmt->rowCount())throw new RuntimeException('Échec introuvable ou déjà relancé.');}
    public function cancel(int$id,int$userId): void {$stmt=$this->db->prepare("UPDATE social_publication_targets t JOIN social_publications p ON p.id=t.publication_id SET t.status='Cancelled' WHERE p.id=:id AND p.tenant_id=:tenant AND t.status IN ('WaitingApproval','Queued','Retrying')");$stmt->execute(['id'=>$id,'tenant'=>TenantGuard::tenantId()]);if(!$stmt->rowCount())throw new RuntimeException('Aucune exécution annulable.');$this->event($id,null,'cancelled','Cancelled','Publication annulée',$userId);}
    private function assertPublishPermission(array$connection): void {if(empty($connection['last_validated_at']))throw new RuntimeException('Cette destination doit être reconnectée à Meta pour vérifier ses droits actuels.');$scopes=(array)json_decode((string)($connection['scopes_json']??'[]'),true);if($connection['provider']==='facebook'&&!in_array('pages_manage_posts',$scopes,true))throw new RuntimeException('La Page Facebook ne dispose pas de pages_manage_posts. Reconnectez Meta.');if($connection['provider']==='instagram'&&!array_intersect(['instagram_content_publish','instagram_business_content_publish'],$scopes))throw new RuntimeException('Le compte Instagram ne dispose pas de la permission de publication. Reconnectez Meta.');}
    private function storeUpload(array$file): array {if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('Import du média impossible.');if((int)($file['size']??0)>20*1024*1024)throw new RuntimeException('Le média dépasse 20 Mo.');$finfo=new finfo(FILEINFO_MIME_TYPE);$mime=(string)$finfo->file((string)$file['tmp_name']);$extensions=['image/jpeg'=>'jpg','image/png'=>'png'];if(!isset($extensions[$mime]))throw new RuntimeException('Formats acceptés : JPEG ou PNG.');$relative='social-publication/'.date('Y/m').'/'.bin2hex(random_bytes(16)).'.'.$extensions[$mime];$absolute=UPLOADS_PATH.'/'.$relative;$directory=dirname($absolute);if(!is_dir($directory)&&!mkdir($directory,0775,true)&&!is_dir($directory))throw new RuntimeException('Impossible de créer le dossier média.');if(!move_uploaded_file((string)$file['tmp_name'],$absolute))throw new RuntimeException('Impossible d enregistrer le média.');$scheme=(!empty($_SERVER['HTTPS'])&&strtolower((string)$_SERVER['HTTPS'])!=='off')?'https':'http';$url=$scheme.'://'.($_SERVER['HTTP_HOST']??'localhost').upload_url($relative);return[$url,$relative,$mime];}
    private function event(int$publication,?int$target,string$type,string$status,string$message,int$user): void {$stmt=$this->db->prepare('INSERT INTO social_publication_events(tenant_id,publication_id,target_id,event_type,status,message,created_by) VALUES(:tenant,:publication,:target,:type,:status,:message,:user)');$stmt->execute(['tenant'=>TenantGuard::tenantId(),'publication'=>$publication,'target'=>$target,'type'=>$type,'status'=>$status,'message'=>$message,'user'=>$user]);}
}