<?php
$organizations = is_array($organizations ?? null) ? $organizations : [];
$memberships = is_array($memberships ?? null) ? $memberships : [];
$agencyCount = count(array_filter($organizations, static fn($item) => ($item['account_type'] ?? '') === 'Agency'));
$registeredCount = count(array_filter($organizations, static fn($item) => ($item['registration_state'] ?? '') === 'Registered'));
?>
<section class="page-intro-card"><div><span class="page-eyebrow">Administration SaaS</span><h2>Entreprises et comptes</h2><p>Gérez les agences, les clients directs, les profils externes et leurs utilisateurs depuis un espace central.</p></div><span class="context-pill"><?= htmlspecialchars($tenant['name'] ?? 'Plateforme') ?></span></section>
<div class="entity-stats-grid four-columns"><article class="entity-stat"><span>Organisations</span><strong><?= count($organizations) ?></strong><small>Total géré</small></article><article class="entity-stat"><span>Agences</span><strong><?= $agencyCount ?></strong><small>Comptes multi-projets</small></article><article class="entity-stat"><span>Comptes SaaS</span><strong><?= $registeredCount ?></strong><small>Organisations inscrites</small></article><article class="entity-stat"><span>Utilisateurs</span><strong><?= count($memberships) ?></strong><small>Memberships actifs ou invités</small></article></div>
<section class="saas-action-grid">
 <article class="panel action-form-card"><div class="panel-head"><div><span class="section-number">01</span><h2>Créer une organisation</h2><p class="panel-subtitle">Entreprise cliente, agence ou profil externe.</p></div></div><form method="post" class="form-grid"><input type="hidden" name="action" value="create_organization"><label class="field"><span>Nom de l’organisation</span><input name="name" required placeholder="Raison sociale"></label><div class="form-grid two-columns"><label class="field"><span>Type de compte</span><select name="account_type"><option value="ClientCompany">Entreprise cliente</option><option value="Agency">Agence</option></select></label><label class="field"><span>Mode projets</span><select name="project_mode"><option value="Single">Projet unique</option><option value="Multiple">Plusieurs projets</option></select></label></div><label class="field"><span>Présence sur la plateforme</span><select name="registration_state"><option value="ExternalProfile">Client externe, sans compte</option><option value="Registered">Compte SaaS actif</option></select></label><button class="button primary" type="submit">Créer l’organisation</button></form></article>
 <article class="panel action-form-card"><div class="panel-head"><div><span class="section-number">02</span><h2>Inviter un utilisateur</h2><p class="panel-subtitle">Rattachez une personne à une organisation existante.</p></div></div><form method="post" class="form-grid"><input type="hidden" name="action" value="invite"><label class="field"><span>Nom complet</span><input name="user_name" autocomplete="name" placeholder="Nom et prénom"></label><label class="field"><span>Adresse email</span><input type="email" name="email" required autocomplete="email" placeholder="nom@entreprise.com"></label><label class="field"><span>Organisation</span><select name="organization_id" required><option value="">Sélectionner une organisation</option><?php foreach ($organizations as $organization): ?><option value="<?= (int) $organization['id'] ?>"><?= htmlspecialchars($organization['name']) ?></option><?php endforeach; ?></select></label><button class="button primary" type="submit">Créer l’invitation</button></form></article>
</section>
<section class="panel entity-list-panel"><div class="panel-head"><div><h2>Répertoire des organisations</h2><p class="panel-subtitle">Structure, présence SaaS et mode de gestion des projets.</p></div><span class="chip"><?= count($organizations) ?> organisation<?= count($organizations)>1?'s':'' ?></span></div><div class="table-wrap"><table class="data-table entity-table"><thead><tr><th>Organisation</th><th>Type</th><th>Présence SaaS</th><th>Mode projets</th><th>Identifiant</th><th>Statut</th></tr></thead><tbody><?php foreach ($organizations as $organization): ?><tr><td><div class="entity-identity"><span class="entity-avatar"><?= htmlspecialchars(strtoupper(substr((string)$organization['name'],0,1))) ?></span><strong><?= htmlspecialchars($organization['name']) ?></strong></div></td><td><?= htmlspecialchars($organization['account_type']) ?></td><td><span class="status-badge"><?= htmlspecialchars($organization['registration_state']) ?></span></td><td><?= htmlspecialchars($organization['project_mode']) ?></td><td><code><?= htmlspecialchars($organization['slug']) ?></code></td><td><span class="status-badge"><?= htmlspecialchars($organization['status']) ?></span></td></tr><?php endforeach; ?><?php if(empty($organizations)): ?><tr><td colspan="6"><div class="empty-state">Aucune organisation enregistrée.</div></td></tr><?php endif; ?></tbody></table></div></section>
<section class="panel entity-list-panel"><div class="panel-head"><div><h2>Utilisateurs et memberships</h2><p class="panel-subtitle">Rôles et état des accès pour chaque organisation.</p></div><span class="chip"><?= count($memberships) ?> membre<?= count($memberships)>1?'s':'' ?></span></div><div class="table-wrap"><table class="data-table entity-table"><thead><tr><th>Utilisateur</th><th>Organisation</th><th>Rôle et statut</th></tr></thead><tbody><?php foreach ($memberships as $membership): ?><tr><td><div class="entity-contact"><strong><?= htmlspecialchars($membership['nom']) ?></strong><small><?= htmlspecialchars($membership['email']) ?></small></div></td><td><?= htmlspecialchars($membership['organization_name'] ?? 'Équipe interne') ?></td><td><form method="post" class="mini-inline-form membership-form"><input type="hidden" name="action" value="update_membership"><input type="hidden" name="membership_id" value="<?= (int)$membership['id'] ?>"><select name="membership_role" aria-label="Rôle"><?php foreach(['Owner','Admin','Manager','Member','Client'] as $role): ?><option value="<?= $role ?>" <?= $membership['membership_role']===$role?'selected':'' ?>><?= $role ?></option><?php endforeach; ?></select><select name="membership_status" aria-label="Statut"><?php foreach(['Invite','Actif','Suspendu'] as $status): ?><option value="<?= $status ?>" <?= $membership['status']===$status?'selected':'' ?>><?= $status ?></option><?php endforeach; ?></select><button class="button secondary button-small" type="submit">Mettre à jour</button></form></td></tr><?php endforeach; ?><?php if(empty($memberships)): ?><tr><td colspan="3"><div class="empty-state">Aucun utilisateur rattaché.</div></td></tr><?php endif; ?></tbody></table></div></section>