<div class="public-page marketing-page">
  <section class="marketing-hero">
    <div class="hero-copy"><span class="eyebrow">Pilotage éditorial multi-entreprises</span><h1>Transformez vos idées en contenus publiés, sans perdre le fil.</h1><p>Strax réunit matrices de création, calendriers mensuels, validations, livrables et performances dans un espace sécurisé pour agences et entreprises.</p><div class="hero-actions"><a class="public-button primary" href="<?= htmlspecialchars(route_url('/public/register')) ?>">Créer mon espace</a><a class="public-button secondary" href="<?= htmlspecialchars(route_url('/login')) ?>">Se connecter</a></div><div class="trust-row"><span>✓ Données cloisonnées</span><span>✓ Accès agence révocable</span><span>✓ Historique partagé</span></div></div>
    <figure class="hero-visual"><img src="<?= htmlspecialchars(app_url('/public/assets/site/hero-team.webp')) ?>" alt="Équipe créative planifiant une campagne de contenu"><figcaption><strong>Une vision partagée.</strong><span>Chaque idée, validation et résultat au même endroit.</span></figcaption></figure>
  </section>
  <section class="feature-section"><header><span class="eyebrow">Un seul flux de travail</span><h2>De la stratégie à la mesure des résultats</h2></header><div class="feature-grid"><article><span>01</span><h3>Composer</h3><p>Configurez vos matrices, générez des combinaisons et enrichissez chaque idée avec son brief ou son script.</p></article><article><span>02</span><h3>Planifier</h3><p>Répartissez les idées validées dans les calendriers mensuels de chaque client et projet.</p></article><article><span>03</span><h3>Collaborer</h3><p>Partagez, validez et autorisez une agence avec des droits précis, sans céder la propriété des données.</p></article><article><span>04</span><h3>Mesurer</h3><p>Centralisez les KPI et conservez l’historique nécessaire aux prochaines décisions éditoriales.</p></article></div></section>
  <section class="outcomes-section"><header><span class="eyebrow">Orienté résultats</span><h2>Moins de dispersion. Plus de décisions qui avancent.</h2><p>Chaque image illustre une étape précise du travail, avec un résultat attendu plutôt qu’une simple fonctionnalité.</p></header><div class="outcome-grid"><article><img loading="lazy" src="<?= htmlspecialchars(app_url('/public/assets/site/approval.webp')) ?>" alt="Validation collaborative d’un livrable"><div><span>Collaborer</span><h3>Des validations qui ne se perdent plus dans les messages.</h3><p>Décisions, commentaires et versions restent liés au bon livrable.</p></div></article><article><img loading="lazy" src="<?= htmlspecialchars(app_url('/public/assets/site/publishing.webp')) ?>" alt="Planification des publications sociales"><div><span>Exécuter</span><h3>Un calendrier qui devient un outil de production.</h3><p>Chaque contenu validé rejoint automatiquement le mois et le projet concernés.</p></div></article><article><img loading="lazy" src="<?= htmlspecialchars(app_url('/public/assets/site/analytics.webp')) ?>" alt="Analyse des résultats d’une campagne"><div><span>Améliorer</span><h3>Les performances nourrissent le prochain cycle.</h3><p>Les KPI restent attachés au client, au contenu et à son historique.</p></div></article></div><a class="text-link" href="<?= htmlspecialchars(route_url('/public/solutions')) ?>">Découvrir le parcours complet →</a></section>  <section class="audience-section"><article><span class="eyebrow">Pour les agences</span><h2>Gérez plusieurs portefeuilles sans mélanger les données.</h2><p>Créez librement des clients externes ou connectez un client inscrit grâce à son autorisation.</p></article><article><span class="eyebrow">Pour les entreprises</span><h2>Gardez votre calendrier, même si votre agence change.</h2><p>Invitez une agence, choisissez ses droits et révoquez son accès à tout moment.</p></article></section>
  <section class="final-cta"><span class="eyebrow">Prêt à structurer votre production ?</span><h2>Créez votre espace sécurisé en quelques minutes.</h2><a class="public-button light" href="<?= htmlspecialchars(route_url('/public/register')) ?>">Commencer maintenant</a></section>
</div>
