<div class="public-page marketing-page">
  <section class="marketing-hero">
    <div class="hero-copy"><span class="eyebrow">Content Operations pour agences et marques</span><h1>Transformez votre stratégie en contenus prêts à produire.</h1><p>Strax réunit matrices de création, banques d’idées, projets, calendriers, briefs et validations dans un espace sécurisé où la marque reste propriétaire de son historique.</p><div class="hero-actions"><a class="public-button primary" href="<?= htmlspecialchars(route_url('/public/register')) ?>">Créer mon espace</a><a class="public-button secondary" href="<?= htmlspecialchars(route_url('/pricing')) ?>">Voir les tarifs</a></div><div class="trust-row"><span>✓ Données cloisonnées</span><span>✓ Accès agence révocable</span><span>✓ Historique conservé</span></div></div>
    <figure class="hero-visual"><img src="<?= htmlspecialchars(app_url('/public/assets/site/hero-team.webp')) ?>" alt="Équipe créative planifiant une campagne de contenu"><figcaption><strong>Une vision partagée.</strong><span>Chaque idée, décision et livrable au même endroit.</span></figcaption></figure>
  </section>
  <section class="feature-section"><header><span class="eyebrow">Un seul flux de travail</span><h2>De la stratégie au calendrier validé</h2></header><div class="feature-grid"><article><span>01</span><h3>Composer</h3><p>Configurez vos matrices et transformez cibles, offres, objectifs et formats en idées structurées.</p></article><article><span>02</span><h3>Enrichir</h3><p>Ajoutez un brief ou un script à chaque idée avant de la transmettre à la production.</p></article><article><span>03</span><h3>Planifier</h3><p>Répartissez les idées validées dans les calendriers mensuels du bon client et du bon projet.</p></article><article><span>04</span><h3>Collaborer</h3><p>Validez les livrables et autorisez une agence avec des droits précis, sans céder vos données.</p></article></div></section>
  <section class="outcomes-section"><header><span class="eyebrow">Orienté résultats</span><h2>Moins de dispersion. Une production plus prévisible.</h2><p>Strax structure le travail que les équipes réalisent déjà entre fichiers, messages et tableurs.</p></header><div class="outcome-grid"><article><img loading="lazy" src="<?= htmlspecialchars(app_url('/public/assets/site/approval.webp')) ?>" alt="Validation collaborative d’un livrable"><div><span>Valider</span><h3>Les décisions restent liées au bon livrable.</h3><p>Commentaires, versions et statuts sont conservés avec le projet.</p></div></article><article><img loading="lazy" src="<?= htmlspecialchars(app_url('/public/assets/site/publishing.webp')) ?>" alt="Planification d’un calendrier éditorial"><div><span>Planifier</span><h3>Le calendrier devient un outil de production.</h3><p>Chaque idée validée rejoint le mois, le client et le projet concernés.</p></div></article><article><img loading="lazy" src="<?= htmlspecialchars(app_url('/public/assets/site/analytics.webp')) ?>" alt="Équipe préparant son prochain cycle éditorial"><div><span>Capitaliser</span><h3>L’historique survit aux changements d’équipe.</h3><p>La marque garde ses matrices, calendriers, livrables et décisions.</p></div></article></div><a class="text-link" href="<?= htmlspecialchars(route_url('/public/solutions')) ?>">Découvrir le parcours complet →</a></section>
  <section class="audience-section"><article><span class="eyebrow">Pour les agences</span><h2>Gérez plusieurs portefeuilles sans mélanger les données.</h2><p>Créez des clients externes ou connectez un client inscrit grâce à son autorisation.</p></article><article><span class="eyebrow">Pour les entreprises</span><h2>Gardez votre espace, même si votre agence change.</h2><p>Invitez une agence, choisissez ses droits et révoquez son accès à tout moment.</p></article></section>
  <section class="roadmap-proof"><div><span class="eyebrow">Déploiement progressif</span><h2>Meta et les KPI sont activés par étapes.</h2><p>La connexion, la publication automatisée et la collecte de performance sont en validation technique. Elles ne sont pas incluses dans la promesse commerciale actuelle.</p></div><a class="public-button secondary" href="<?= htmlspecialchars(route_url('/pricing')) ?>">Découvrir les offres fondatrices</a></section>
  <section class="final-cta"><span class="eyebrow">Prêt à structurer votre production ?</span><h2>Créez votre espace sécurisé en quelques minutes.</h2><a class="public-button light" href="<?= htmlspecialchars(route_url('/public/register')) ?>">Commencer maintenant</a></section>
</div>
