<div class="public-page solutions-page">
 <section class="solutions-hero"><span class="eyebrow">Du brief au résultat</span><h1>Un système opérationnel, pas une couche de plus.</h1><p>Strax relie les décisions, la production et les données pour que chaque équipe sache quoi faire, pour quel client et avec quel niveau d’autorisation.</p></section>
 <section class="solution-journey">
  <article><div><span class="journey-number">01</span><h2>Construire une stratégie exploitable</h2><p>Les matrices transforment cibles, produits, objectifs et formats en idées structurées. Chaque idée peut embarquer son brief ou son script dès sa création.</p><ul><li>Banques d’idées réutilisables</li><li>Combinaisons automatiques contrôlées</li><li>Formats adaptés à chaque canal</li></ul></div><img src="<?= htmlspecialchars(app_url('/public/assets/site/generated-02.webp')) ?>" alt="Planification stratégique de contenus"></article>
  <article><div><span class="journey-number">02</span><h2>Produire sans perdre les validations</h2><p>Les livrables, commentaires et décisions restent attachés au projet et au calendrier du client, même lorsqu’une agence intervient.</p><ul><li>Briefs et scripts centralisés</li><li>Validation interne et client</li><li>Historique consultable</li></ul></div><img src="<?= htmlspecialchars(app_url('/public/assets/site/product-studio.webp')) ?>" alt="Production professionnelle d’un contenu"></article>
  <article><div><span class="journey-number">03</span><h2>Publier puis apprendre</h2><p>Une fois validés, les contenus rejoignent le calendrier de publication. Les KPI reviennent ensuite dans le même contexte pour guider le mois suivant.</p><ul><li>Calendriers mensuels synchronisés</li><li>Publication et collecte connectables</li><li>Analyse par client et projet</li></ul></div><img src="<?= htmlspecialchars(app_url('/public/assets/site/analytics.webp')) ?>" alt="Équipe analysant les performances éditoriales"></article>
 </section>
 <section class="security-proof"><img src="<?= htmlspecialchars(app_url('/public/assets/site/secure-sync.webp')) ?>" alt="Connexion sécurisée entre une agence et son client"><div><span class="eyebrow">La donnée reste chez le client</span><h2>Une collaboration réversible par conception.</h2><p>Une agence ne voit que les périmètres autorisés. Le client peut modifier les droits ou révoquer l’accès sans perdre son historique.</p><a class="public-button primary" href="<?= htmlspecialchars(route_url('/public/register')) ?>">Créer mon espace</a></div></section>
</div>
